version: '3.8'

services:
  api:
    container_name: animal-service/api
    build: ./
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: animal-service/mysql
    image: mysql:8.0.27
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
