version: '3.9'

services:
  api:
    container_name: api
    build: ./
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql
    image: mysql:8.0.27
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
