version: '3.8'

services:
  api:
    container_name: api
    build: ./
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8.0.27
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
